sudo: false
language: android

env:
  global:
    - MALLOC_ARENA_MAX=2

android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - 'android-sdk-license-.+'

before_script:
    - export GRADLE_OPTS="-XX:MaxPermSize=2048m -Xmx1536m"

script:
    - ./gradlew clean build -PdisablePreDex